WAWIA/WAWIA/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pollingSite.urls')),
]

WAWIA/pollingSite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth.urls import views as auth_views
from . import views


app_name = 'pollingSite'
urlpatterns = [
    path('', views.landing, name='landing'),
    path('index/', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='pollingSite/login.html'), name='login'),
    path('change-password/password_change_done/', auth_views.PasswordChangeDoneView.as_view(template_name='pollingSite/changePasswordComplete.html'), name='password_change_done'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='pollingSite/changePassword.html', success_url='password_change_done/'), name='changePassword'),
	path('receive_sms/', views.recieveSMS, name='sms'),
    path('addclass/', views.addClass, name='addClass'),
    path('report/', views.report, name='report'),
    path('poll/', views.pollLanding, name='pollLanding'),
    path('editclass/<int:classroom>/', views.edit, name='edit'),
    path('setActive/<int:classroom>/', views.setActive, name='setActive'),
    path('poll/<str:classroom>/createpoll/', views.createPoll, name='createPoll'),
    path('poll/<str:classroom>/<int:poll>/active/', views.activePoll, name='activePoll'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WAWIA/pollingSite/models.py
from string import ascii_uppercase, digits
from random import choices
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime

SEASONS = ((0,"Winter"), (1,"Spring"), (2,"Summer"), (3,"Fall"))

class InstructorUser(AbstractUser):
    activeClass = models.OneToOneField('Classroom', blank = True, on_delete=models.SET_NULL, null=True)

class Student(models.Model):
    name = models.CharField(max_length = 128)
    lastname = models.CharField(max_length = 128)
    phoneNumber = models.CharField(max_length = 128, null=True)
    def __str__(self):
        return self.name


class Classroom(models.Model):
    className = models.CharField(max_length = 64)
    classKey = models.CharField(max_length = 6, unique=True)

    students = models.ManyToManyField(Student)

    class Meta:
        ordering = ('className',)

    quarter = models.IntegerField(choices=SEASONS)
    year = models.IntegerField(choices=[(i,i) for i in range(2018, datetime.now().year + 1)])
    instructor = models.ForeignKey(InstructorUser, on_delete=models.SET_NULL, null=True) #change on_delete
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)

    def __str__(self):
        return self.className

    def __init__(self, *args, **kwargs):
        super(Classroom, self).__init__(*args, **kwargs)
        if(self.classKey == ''):
            chars = ascii_uppercase + digits
            self.classKey = ''.join(choices(chars, k=5))

    def isActive(self):
        if datetime.now().date() > self.end_date or datetime.now().date() < self.start_date:
            return False
        else:
            return True

class Poll(models.Model):
    options = models.IntegerField()
    correct = models.IntegerField(default=0)
    classroom = models.ForeignKey(Classroom, on_delete=models.CASCADE, null=True)
    startTime = models.DateTimeField(editable=True,blank=True, null=True)
    stopTime = models.DateTimeField(editable=True,blank=True, null=True)
    isPollActive = models.BooleanField(default=False)
    submit = models.BooleanField(default=False)

class Answer(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    value = models.IntegerField()
    timestamp = models.DateTimeField()
    def __str__(self):
        return '{} + {}'.format(self.student, self.poll)

WAWIA/pollingSite/forms.py
from django import forms
from datetime import datetime
from .models import SEASONS, Classroom
from django.contrib.auth.models import User
from django.db.models import Count, Q

class createClassForm(forms.Form):
    class_name = forms.CharField(max_length=50)
    quarter = forms.ChoiceField(choices=SEASONS)
    year = forms.ChoiceField(choices=[(i,i) for i in range(2018, datetime.now().year + 2)])
    start_date = forms.DateField(widget=forms.SelectDateWidget)
    end_date = forms.DateField(widget=forms.SelectDateWidget)
    start_time = forms.TimeField(label="Start Time (24hr)", widget=forms.TimeInput({"placeholder":"HH:MM"},format='%H:%M'))
    end_time = forms.TimeField(label="End Time (24hr)", widget=forms.TimeInput({"placeholder":"HH:MM"},format='%H:%M'))

class editClassForm(forms.ModelForm):
    class Meta:
        model = Classroom
        fields = ['className', 'quarter', 'year', 'start_date', 'end_date', 'start_time', 'end_time']

    start_date = forms.DateField(widget=forms.SelectDateWidget)
    end_date = forms.DateField(widget=forms.SelectDateWidget)
    start_time = forms.TimeField(label="Start Time (24hr)", widget=forms.TimeInput({"placeholder":"HH:MM"}, format='%H:%M'))
    end_time = forms.TimeField(label="End Time (24hr)", widget=forms.TimeInput({"placeholder":"HH:MM"}, format='%H:%M'))

class createPollForm(forms.Form):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(createPollForm, self).__init__(*args, **kwargs)
        self.fields['choose_class'] = forms.ModelChoiceField(queryset=Classroom.objects.filter(instructor=user))

    choose_class = forms.ModelChoiceField(queryset=Classroom.objects.none())
    possible_answers = forms.ChoiceField(choices=[(i,i) for i in range(2,13)], label="# of options for this poll")

class correctAnswerForm(forms.Form):
    correct_answer = forms.CharField(max_length=1)

class reportForm(forms.Form):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super(reportForm, self).__init__(*args, **kwargs)
        self.fields['choose_class'] = forms.ModelChoiceField(queryset=Classroom.objects.filter(instructor=user))

    choose_class = forms.ModelChoiceField(queryset=Classroom.objects.none())
    start_date = forms.DateField(widget=forms.SelectDateWidget)
    end_date = forms.DateField(widget=forms.SelectDateWidget)

WAWIA/pollingSite/views.py
import uuid
import itertools
import operator
import hashlib

from datetime import datetime, timedelta,date
from django import template
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.utils.crypto import get_random_string
from django.utils.timezone import now
from django.utils import timezone
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import login as authLogin
from django.views.decorators.csrf import csrf_exempt
from django.db.models.functions import Trunc

from .models import *
from .forms import *

import traceback

register = template.Library()

def classroomSecureWrapper(function):
    def decorator(request, *args, **kwargs):
        classroom = Classroom.objects.get(pk=kwargs['classroom'])
        if classroom.instructor == request.user:
            return function(request, *args, **kwargs)
        else:
            raise Http404
    return decorator

@csrf_exempt
def recieveSMS(request):
    if request.method == 'POST':
        #save inbound text into variable
        holdText = request.POST['Text']
        

        #holdText = "2"
        studentNumber = hashlib.sha224(request.POST['From'].encode('utf-8')).hexdigest()

        #parse text into a list
        incoming_text = holdText.split(" ")
        if(len(incoming_text) == 3):  # Update takes 3 arguments
            #check if first element is "Update". if it is not, then return
            if(incoming_text[0].lower() == "update"):
                #update
                try:
                    stud = Student.objects.get(phoneNumber=studentNumber)
                    stud.name=incoming_text[1]
                    stud.last_name=incoming_text[2]
                    stud.save()
                    #print("student {0} got updated".format(stud.name))
                    return HttpResponse("Message Recieved")
                except:
                    return HttpResponse("Message Not Recieved")
                    #print("An error occured when trying to update student")
                    #traceback.print_exc()

        elif(len(incoming_text) == 4):
            if(incoming_text[0].lower() == "register"):  # Register takes 4 arguments
                # check if the student is already registered
                # get the classroom connected to the class key the student entered
                try:
                    #check if the class they want to register to exists. if so save it
                    #print(Classroom.objects.filter(classKey=incoming_text[4].upper()).count())
                    if(Classroom.objects.filter(classKey=incoming_text[3].upper()).count() > 0):
                        classWantToRegisterTo = Classroom.objects.get(classKey=incoming_text[3].upper())
                        #print(classWantToRegisterTo)
                        # try to get the existing student from that class to later update it with new info
                        if(Student.objects.filter(phoneNumber=studentNumber).count() > 0): #if student exists
                            tempStudent = Student.objects.get(phoneNumber=studentNumber)
                            #print(tempStudent)
                            # if class exists
                            if(Classroom.objects.filter(students__phoneNumber__startswith=studentNumber).count() > 0):
                                allStudentClasses = Classroom.objects.filter(students__phoneNumber__startswith=studentNumber)
                                #print(allStudentClasses)
                                for item in allStudentClasses:
                                    if(item == classWantToRegisterTo):
                                        #print("Student already in class")
                                        pass
                                    else:
                                        classWantToRegisterTo.students.add(tempStudent)
                                        classWantToRegisterTo.save()
                                        return HttpResponse("Message Recieved")
                                        #print("added student to class")
                        else:
                            #print("The student did not exist. Will now try to create student with info")
                            try:
                                # if the student doesnt exist, try creating a new student and adding it to the class
                                studentCreate = Student.objects.create(name=incoming_text[1], lastname=incoming_text[2], phoneNumber=studentNumber)
                                #print("student: {}".format(studentCreate))
                                # save class the student wants to register to
                                classWantToRegisterTo = Classroom.objects.get(classKey=incoming_text[3].upper())
                                #print("class want to register to: {}".format(classWantToRegisterTo))
                                # add student to that class
                                classWantToRegisterTo.students.add(studentCreate)
                                classWantToRegisterTo.save()
                                return HttpResponse("Message Recieved")
                                #print("The student was added successfully")
                            except:
                                return HttpResponse("Message Not Recieved")
                    else:
                        #print("class does not exist. Will return message not recieved")
                        return HttpResponse("Message Not Recieved")
                except:
                    #print("An error occured. Will return message not recieved")
                    #traceback.print_exc()
                    return HttpResponse("Message Not Recieved")
        elif(len(incoming_text) != 1):
            #print("Not correct number of arguments needed. 1 argument needed")
            #return render(request, 'pollingSite/test.html',locals())
            return HttpResponse("Message Not Recieved")
        else:  # so if argument is 1
            studentAnswerLetter = holdText#incoming_text[0]
            #print(studentAnswerLetter)
            studentAnswer = 0  #initilize studentAnswer

            if(studentAnswerLetter == "A"):
                studentAnswer = 1
            elif(studentAnswerLetter == "B"):
                studentAnswer = 2
            elif(studentAnswerLetter == "C"):
                studentAnswer = 3
            elif(studentAnswerLetter == "D"):
                studentAnswer = 4
            elif(studentAnswerLetter == "E"):
                studentAnswer = 5
            elif(studentAnswerLetter == "F"):
                studentAnswer = 6
            elif(studentAnswerLetter == "G"):
                studentAnswer = 7
            elif(studentAnswerLetter == "H"):
                studentAnswer = 8
            elif(studentAnswerLetter == "I"):
                studentAnswer = 9
            elif(studentAnswerLetter == "J"):
                studentAnswer = 10
            elif(studentAnswerLetter == "K"):
                studentAnswer = 11
            elif(studentAnswerLetter == "L"):
                studentAnswer = 12
            elif(studentAnswerLetter == "M"):
                studentAnswer = 13
            elif(studentAnswerLetter == "N"):
                studentAnswer = 14
            elif(studentAnswerLetter == "O"):
                studentAnswer = 15
            elif(studentAnswerLetter == "P"):
                studentAnswer = 16
            elif(studentAnswerLetter == "Q"):
                studentAnswer = 17
            elif(studentAnswerLetter == "R"):
                studentAnswer = 18
            elif(studentAnswerLetter == "S"):
                studentAnswer = 19
            elif(studentAnswerLetter == "T"):
                studentAnswer = 20
            elif(studentAnswerLetter == "U"):
                studentAnswer = 21
            elif(studentAnswerLetter == "V"):
                studentAnswer = 22
            elif(studentAnswerLetter == "W"):
                studentAnswer = 23
            elif(studentAnswerLetter == "X"):
                studentAnswer = 24
            elif(studentAnswerLetter == "Y"):
                studentAnswer = 25
            elif(studentAnswerLetter == "Z"):
                studentAnswer = 26
            else:
                #return (answer was not valid)
                #print("The argument is not valid")
                return HttpResponse("Message Not Recieved")

            #try to get student depending on phone number
            try:
                studentIdentifier = Student.objects.get(phoneNumber=studentNumber)
                #print(studentIdentifier)
            except:
                #print("The student does not exist (has not registered)")
                return HttpResponse("Message Not Recieved")

            studentClassroom = Classroom.objects.filter(students=studentIdentifier)
            #print("student classroom: {}".format(studentClassroom))

            currentTime = datetime.now()
            #currentTime = currentTime.replace(hour=19, minute=1) #comment before final
            #currentTime = datetime.combine(currentTime, datetime.min.time())
            thereIsAClassCurrently = False

            for current_class in studentClassroom:
                #print("Current Class (checking): {}".format(current_class))
                # get classroom start time
                classroom_start = datetime.now()
                classroom_start = classroom_start.replace(hour=(current_class.start_time.hour), minute=(current_class.start_time.minute))

                # get classroom end time
                classroom_end = datetime.now()

WAWIA/pollingSite/templates/pollingSite/activePoll.html
{% extends 'pollingSite/base.html' %}
{% load static pollingSite_tags %}
{% block content %}
<label style="text-align:center"><font size="6"><b>Polling in {{ request.user.activeClass }}</b></font></label>
<label style="text-align:center"><font size="5" style="color:#990000"><b>Text: 509-303-4655</b></font></label>
<label style="text-align:center"><font size="5" style="color:#990000"><b>Class Key: {{request.user.activeClass.classKey}}</b></font></label>
<div class="row">
    <div class="two columns"><label style="text-align:right; font-size:xx-large"><b>&nbsp;</b></label></div>
    <div class="five columns"><label style="text-align:right; font-size:xx-large"><b><text >Total Submissions:</b></label></div>
    <div class="two columns" ><label id="text6"style="text-align:right; font-size:xx-large"><b>{{totalSub}}</b></label></div>
</div>


    <div class="row">

        {% if poll.correct == 0 and poll.stopTime < poll.startTime %}
        <div class="row">
            <div class="four columns"><label><b>&nbsp;</b></label></div>
            <div class="four columns"><button onclick="myFunction('text8')" style="background-color: #990000"> Show/Hide Answers </button></div>
            <div class="four columns"><label><b>&nbsp;</b></label></div>
        </div>
        
        </div>
<div class="text8" style="display:none">
    <div class="text7">
        <div class="row">
            <div class="two columns answer"><label style="text-align:right;font-size:x-large"><b>Option</b></label></div>
            <div class="five columns answer"><label style="text-align:right;font-size:x-large"><b>Total Answers for Option</b></label></div>
        </div>
        {% for option in options %}

        <div id="" class="row">
            {% if forloop.counter == poll.correct %}
            <div id="answer" class="two columns answer" style="display:block"><label style="text-align:right; color:green; font-size:xx-large"><b>{{ forloop.counter|to_char }}.</b></label></div>
            <div class="four columns answer" style="display:block"><label id="text4" style="text-align:right; color:green; font-size:xx-large"><b>{{ option }}</b></label></div>
            {% else %}
            <div class="two columns answer" style="display:block"><label style="text-align:right; font-size:xx-large"><b>{{ forloop.counter|to_char }}.</b></label></div>
            <div class="four columns answer" style="display:block"><label id="text5" style="text-align:right; font-size:xx-large"><b>{{ option }}</b></label></div>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    </div>
    <form method="post" style="border-color:white">

        <div class="row fin" id="Stop" style="display:block">
            <div class="four columns"><label><b>&nbsp;</b></label></div>
            <div class="four columns"><button type="submit" onclick="myFunction('fin');" style="background-color: #990000"> Enter Correct Answer </button></div>
            <div class="four columns"><label><b>&nbsp;</b></label></div>
        </div>
        <div class="row fin" id="Close" style="display:none">
            {% csrf_token %}
            {{form.as_table}}
            <div class="row">
                <div class="four columns"><label><b>&nbsp;</b></label></div>
                <div class="four columns"><a style="text-decoration:none; color:inherit"><button type="submit" style="background-color: #990000"> Close Poll </button></a></div>
                <div class="four columns"><label><b>&nbsp;</b></label></div>
            </div>
        </div>
    </form>
    {% elif poll.correct == 0 and poll.stopTime > poll.startTime %}
    <div class="row">
        <div class="four columns"><label><b>&nbsp;</b></label></div>
        <div class="four columns"><button onclick="myFunction('answer')" style="background-color: #990000"> Toggle Answers </button></div>
        <div class="four columns"><label><b>&nbsp;</b></label></div>
    </div>
    <div class="two columns answer" style="display:none"><label style="text-align:right;font-size:x-large"><b>Option</b></label></div>
    <div class="five columns answer" style="display:none"><label style="text-align:right;font-size:x-large"><b>Total Answers for Option</b></label></div>
</div>
        {% for option in options %}
<div id="answers" class="row">
    {% if forloop.counter == poll.correct %}
    <div class="two columns answer" style="display:none"><label style="text-align:right; color:green; font-size:xx-large"><b>{{ forloop.counter|to_char }}.</b></label></div>
    <div class="four columns answer" style="display:none"><label style="text-align:right; color:green; font-size:xx-large"><b>{{ option }}</b></label></div>
    {% else %}
    <div class="two columns answer" style="display:none"><label style="text-align:right; font-size:xx-large"><b>{{ forloop.counter|to_char }}.</b></label></div>
    <div class="four columns answer" style="display:none"><label style="text-align:right; font-size:xx-large"><b>{{ option }}</b></label></div>
    {% endif %}
</div>
        {% endfor %}
<form method="post" style="border-color:white">

    <div class="row fin" id="Close" style="display:block">
        {% csrf_token %}
        {{form.as_table}}
        <div class="row">
            <div class="four columns"><label><b>&nbsp;</b></label></div>
            <div class="four columns"><a style="text-decoration:none; color:inherit"><button type="submit" style="background-color: #990000"> Close Poll </button></a></div>
            <div class="four columns"><label><b>&nbsp;</b></label></div>
        </div>
    </div>
</form>
{% else %}
        {% for option in options %}
        <div id="answers" class="row">
            {% if forloop.counter == poll.correct %}
            <div class="one column"><label style="text-align:right; color:green; font-size:xx-large"><b>{{ forloop.counter|to_char }}.</b></label></div>
            <div class="one column"><label style="text-align:right; color:green; font-size:xx-large"><b>{{ option }}</b></label></div>
            {% else %}
            <div class="one column"><label style="text-align:right; font-size:xx-large"><b>{{ forloop.counter|to_char }}.</b></label></div>
            <div class="one column"><label style="text-align:right; font-size:xx-large"><b>{{ option }}</b></label></div>
            {% endif %}
        </div>
        {% endfor %}
        <div class="row">
            <div class="four columns"><label><b>&nbsp;</b></label></div>
            <div class="four columns"><a style="text-decoration:none; color:inherit" href="{% url 'pollingSite:createPoll' classroom %}"><button type="button" style="background-color: #990000"> Run New Poll</button></a></div>
            <div class="four columns"><label><b>&nbsp;</b></label></div>
        </div>
        
        {% endif %}


    {% endblock content %}

{% block JavaScrpt %}
<script src="{% static 'pollingSite/JavaScript/ToggleVisable.js' %}"></script>
{% endblock JavaScrpt %}

WAWIA/pollingSite/templates/pollingSite/changePasswordComplete.html
{% extends 'pollingSite/base.html' %}
{% block content %}
    <label style="text-align:center"><font size="6"><b>Change Password Done</font></label>
    <label style="text-align:center"><font size="4"><b>Returning Home</font></label>
{% endblock content %}

{% block JavaScrpt %}
<script>
$(document).ready(function(){
    setInterval(function() {
        window.location.replace("{% url 'pollingSite:index' %}")
    }, 5000);
});
</script>
{% endblock JavaScrpt %}

WAWIA/pollingSite/templates/pollingSite/createPoll.html
{% extends 'pollingSite/base.html' %}
{% block content %}
<label style="text-align:center"><font size="6"><b>Create a poll for {{ classroom.className }}</b></font></label>

<form method="post"style="border-color:white">

    {% csrf_token %}
        {{form.as_table}}
<div class="row">
    <button type="submit" style="background-color: #990000">Run Poll</button>
</div>
</form>
{% endblock content %}

WAWIA/pollingSite/templates/pollingSite/homebar.html
<div class="row">
        <div class="four columns">&nbsp;</div>
        <div class="eight columns">
            {% if 'index/' in request.path or 'editclass/' in request.path %}
            <div class="four columns"><a href="{% url 'pollingSite:index' %}"><button type="submit" style="background-color: #990000"><b>Classes</b></button></a></div>
            {% else %}
            <div class="four columns"><a href="{% url 'pollingSite:index' %}"><button type="submit"><b>Classes</b></button></a></div>
            {% endif %}
            {% if 'addclass/' in request.path%}
            <div class="four columns"><a href="{% url 'pollingSite:addClass' %}"><button type="submit" style="background-color: #990000"><b>Add Class</b></button></a></div>
            {% else %}
            <div class="four columns"><a href="{% url 'pollingSite:addClass' %}"><button type="submit"><b>Add Class</b></button></a></div>
            {% endif %}
            {% if 'change-password/' in request.path %}
            <div class="four columns"><a href="{% url 'pollingSite:changePassword' %}"><button type="submit" style="background-color: #990000"><b>Change Password</b></button></a></div>
            {% else %}
            <div class="four columns"><a href="{% url 'pollingSite:changePassword' %}"><button type="submit"><b>Change Password</b></button></a></div>
            {% endif %}
        </div>
</div>

WAWIA/pollingSite/templates/pollingSite/index.html
{% extends 'pollingSite/base.html' %}

{% block content %}

<div class="row">
    <label style="text-align:center"><font size="6"><b>Whose Answer Was It Anyways?</b></font></label>
         {% include 'pollingSite/homebar.html' %}
             <div class="row"><b>To Register Text: Register FirstName LastName (class key) to 509-303-4655</b></div>
    <div class="row"><b>To Update Info Text: Update FirstName LastName</b></div>
    <div class="row"><b>To Answer a Poll: Simply text the letter of the answer</b></div>
        {% for class in classroom %}
        {% ifchanged class.quarter or class.year %}
        <div class="row">
            <br />
            <font size="6" style="">
                <u>{{ class.get_quarter_display }} {{ class.year }}</u>
            </font>
            <br />
        </div>
        <div class="row">
            <div class="three columns"><u><b>Active Class</b></u></div>
            <div class="three columns">
                <font size="3"><u>Class Name</u></font>
            </div>
            <div class="three columns">
                <font size="3">
                    <u>Class Key </u>
                </font>
            </div>
        </div>
        {% endifchanged %}
        {% if forloop.counter0|divisibleby:2 %}
        <div class="row" style="background-color:#E5E5E5">
            {% else %}
            <div class="row">
                {% endif %}
                {% if class.isActive %}
                {% if request.user.activeClass == class %}
                <div class="three columns"><a href="{% url 'pollingSite:setActive' class.id %}"><input type="radio" name="select" checked style="margin-left:50%"></input></a></div>
                {% else %}
                <div class="three columns"><a href="{% url 'pollingSite:setActive' class.id %}"><input type="radio" name="select" style="margin-left:50%"></input></a></div>
                {% endif %}
                {% else %}
                <div class="three columns">&nbsp;</div>
                {% endif %}
                <div class="three columns">
                    <font size="3">{{ class.className }}</font>
                </div>
                <div class="three columns">
                    <font size="3">
                        <font style="color:#990000">{{class.classKey}}</font>
                    </font>
                </div>
                <div class="three columns">
                    <a href="{% url 'pollingSite:edit' class.id %}">Edit</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endblock content%}

WAWIA/pollingSite/templates/pollingSite/navbar.html
<div class="row">
    {% if 'index/' in request.path or 'addclass/' in request.path or 'change-password/' in request.path  or 'editclass/' in request.path %}
        <div class="three columns"><a href="{% url 'pollingSite:index' %}"><button type="submit" style="background-color: #990000"><b>Home</b></button></a></div>
    {% else %}
        <div class="three columns"><a href="{% url 'pollingSite:index' %}"><button type="submit"><b>Home</b></button></a></div>
    {% endif %}
    {% if 'poll/' in request.path %}
        <div class="three columns"><a href="{% url 'pollingSite:pollLanding' %}"><button type="submit" style="background-color: #990000">Poll</button></a></div>
    {% else %}
        <div class="three columns"><a href="{% url 'pollingSite:pollLanding' %}"><button type="submit">Poll</button></a></div>
    {% endif %}
    {% if 'report/' in request.path %}
    <div class="three columns"><a href="{% url 'pollingSite:report' %}"><button type="submit" style="background-color: #990000"><b>Report</b></button></a></div>
    {% else %}
    <div class="three columns"><a href="{% url 'pollingSite:report' %}"><button type="submit"><b>Report</b></button></a></div>
    {% endif %}
    <div class="three columns"><a href="{% url 'pollingSite:logout' %}"><button type="submit"><b>Log Out</b></button></a></div>
</row>

WAWIA/pollingSite/templates/pollingSite/test.html
{% load static %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link rel="stylesheet" href="{% static 'pollingSite/css/skeleton.css' %}">
    <link rel="stylesheet" href="{% static 'pollingSite/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'pollingSite/css/WAWIA.css' %}">
    {% block css %}{% endblock css %}

    <meta charset="utf-8" />
    <title></title>
</head>
{% block body %}
<body>
    <div class="container" >

        <!-- columns should be the immediate child of a .row -->
        <div class="row">
            <div class="three columns"><a href="{% url 'pollingSite:index' %}"><button type="submit" >Home</button></a></div>
            
            <div class="three columns"><a href="{% url 'pollingSite:changePassword' %}"><button type="submit"style="background-color: #990000">Change Password</button></a></div>
            <div class="three columns"><a href="{% url 'pollingSite:logout' %}"><button type="submit">Log Out</button></a></div>
       </div>
       {% block content %}{% endblock content %}
    </div>
    {% block JavaScrpt %}{% endblock JavaScrpt %}
    <form method="post">
      <button type="submit">Test</button>
    </form>

</body>
{% endblock body %}

</html>